PROJECT:=Beamer

include makefile-latex/latex-std-dependence.mk
DEPS_MAIN_TEX:=${STYS_MINIMUS} ${CLSS_BEAMER_BISMUTH}
DEPS_FIGS_TEX:=${STYS_MINIMUS} ${CLSS_STANDALONE_SILICON}

include makefile-latex/makefile-latex.mk
